### ISSUE TITLE
ImportError: cannot import name singularity_index

### ISSUE THREAD

**Issue by shCampos** [isikdogan/rivamap#1]
Hello
I'm working with Anaconda and Python 2.7. I installed all the dependencies and the library correctly, but when I go to test it appears the error:
 
`File "rivamap.py", line 11, in <module>`
`from rivamap import singularity_index, delineate, preprocess, georef, visualization`
`ImportError: cannot import name singularity_index`

Thanks for the help :)

**Comment by isikdogan** [comment]
Hello. That's unusual. Did you use PyPI to install the package? If not, make sure that the rivamap folder is either in your path or in the working directory.

**Comment by geodan643** [comment]
Hi, I'm trying to use rivaMap in Colab with conda, but I can't install the package. The following message appears:

PackagesNotFoundError: The following packages are not available from current channels:

  - rivamap

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
